#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x mpd > /dev/null || mpd &

picom --experimental-backends &
~/.config/polybar/launch.sh &
~/.fehbg &

bspc monitor -d I II III IV V

bspc config border_width        5
bspc config window_gap          5

bspc config split_ratio         0.52
bspc config gapless_monocle     false
bspc config borderless_monocle  false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
